### ISSUE TITLE
Show Issues from httpd instead of mock data

### ISSUE THREAD

**Issue by maninak** [cytechmobile/radicle-planning-boards#18]
Working on this most probably implies that the Issues will be created either via the terminal or the Radicle web app.

We should use some kind of systematic encoding of the column each label belongs to, ideally as namespaced labels. E.g. `RPBː<varName>ː<varType>ː<JSON.stringify(varName)>`. Note that the separator I used here is [the unicode char U+02D0](https://unicode-explorer.com/c/02D0) which I thought would help us avoid collisions with content.
Example: `RPBː"column"ː"string"ː"To-Do"` or `RPBː"priority"ː"number":5` etc

We should ensure those labels are not shown in the UI by default, unless `RPB_config-show-data-labels` is set in the LocalStorage with the value `"true"`. Anything else should imply false (default).

We should probably also set `editor.unicodeHighlight.ambiguousCharacters` to `true` inside `.vscode/settings.json`.

**Resources:**

- [`useLocalStorage()`](https://vueuse.org/core/useLocalStorage/) from VueUse

Requires #6

**Comment by QZera** [comment]
> We should ensure those labels are not shown in the UI by default, unless RPB_config-show-data-labels is set in the LocalStorage with the value "true". Anything else should imply false (default).

1. We currently don't display any labels on the issue cards, should we add them as part of this issue?
2. Did you have in mind some kind of UI toggle for the LocalStorage flag, or just leave it be toggled manually?

> `RPBː<varName>ː<varType>ː<JSON.stringify(varName)>`

Could we omit the `varType` (`RPBː<varName>ː<JSON.stringify(varName)>`)?
I think we can rely on the name to know the type of each label.

**Comment by maninak** [comment]
1. Let's skip showing other labels. For this, we only need to parse _all_ Issues looking for specific labels to infer the Columns which Issues to list under it. Doing it performantly is a consideration, but mostly in terms of not steps making it blatalntly needlesly slow, for now.

    One option is to only look for labels corresponding to the Columns we already use. Another could be listing all other non-matching Issues in a leftmost column for visibility, similarly to how GitHub lists them. We could call that Column "Non-planned" perhaps also in italics.

    ![image](https://github.com/cytechmobile/radicle-planning-boards/assets/7542054/6babdfd2-8c57-4c42-9aa6-1284d0d14824)

2. Nah let's leave the configs in the localstorage only. We have a component library that could help build a modal on a keystroke (e.g. `Ctrl +,`) quite fast, but honestly, it will all be wasted work. That's a debugging mode anyway.

**Comment by QZera** [comment]
@gsaslis I'd like your insight regarding the columns

For the prototype, should we only display columns found in issue labels? (e.g. if there are only `todo` and `done` issues, only those columns would be displayed)
Or should the `todo`, `done`, `doing` columns always be displayed?

This was brought up recently in [this PR discussion](https://github.com/cytechmobile/radicle-planning-boards/pull/27#discussion_r1426019546)

**Comment by gsaslis** [comment]
It's enough to always just show the 3 columns

**Comment by maninak** [comment]
The important thing for me is ylthat our algorithm is the one we'd use if we were to show all columns, i.e. group issues by column data label.
That algorithm should also result in simpler code overall than now. And at that point only showing 3 columns would add complexity albeit minimal. I suggest we implement showing _at least_ our three columns.

**Comment by gsaslis** [comment]
> The important thing for me is that our algorithm is the one we'd use if we were to show all columns, i.e. group issues by column data label.

@maninak this is not a requirement for the prototype that I am trying to have delivered. 


Let me once again remind you

**Comment by QZera** [comment]
# Results

- Implemented functionality to fetch issues from the given repo (instead of using mock data), and sort them into their respective columns based on their data label (`RPB:column:{todo|doing |done}`)
- Added the `non-planned` column for issues that don't have a column data label
- Added a localstorage flag for debugging data labels (`RPB_config-show-data-labels`)



![Image](https://github.com/cytechmobile/radicle-planning-boards/assets/15063937/0112eeb2-7071-4b8e-ab46-512723746a89)
