### ISSUE TITLE
Moving a card across columns is saved on Radicle

### ISSUE THREAD

**Issue by maninak** [cytechmobile/radicle-planning-boards#19]
When dragging an Issue from one column to another, we should save this updated state on Radicle itself (e.g. as a Label on the Issue. Our app's UI should also reflect this updated state.

Requires #18 and #7

**Comment by QZera** [comment]
@gsaslis I'm currently facing [this issue](https://radicle.zulipchat.com/#narrow/stream/369873-support/topic/.E2.9C.94.20Not.20able.20to.20add.20assignees.20or.20labels.20due.20to.20authorization/near/393755137).

 Could you make me a delegate for `radicle-planning-boards`?

Something to keep in mind: this will also affect the demo, as users will need to be delegates on the project they're updating.

**Comment by maninak** [comment]
@gsaslis I created and accepted a new revision adding Zac to delegates which also increases the threshold from `1` to `2`.

To show it: `rad sync -f && rad id show 92df448`
To accept it: `rad id accept 92df448 && rad sync -a`

**Comment by gsaslis** [comment]
@QZera would creating a new repo and using that for your tests work around this ?

**Comment by QZera** [comment]
# Results

Added support for persisting which column an issue is in by updating its labels through httpd.


https://github.com/cytechmobile/radicle-planning-boards/assets/15063937/f0f0d3a4-30d8-47f1-9c71-03418691299d
