### ISSUE TITLE
Show the status of an Issue on its card

### ISSUE THREAD

**Issue by maninak** [cytechmobile/radicle-planning-boards#20]
The status of a Radicle Issue can be [`"open"` or `"closed"`](https://app.radicle.xyz/seeds/seed.rhizoma.dev/rad:z3yQUb9HDAC7TQrUDGkQsXDsYFj9G/tree/master/api/radicle-httpd.yaml#L1221).

Irrespective of on which column an Issue card is shown, we should also communicate the status of it, perhaps with an icon.

We should try to use a different icon for open and closed issues and perhaps also a different color (whichever is used by radicle-interface). Depending _solely_ on color to communicate state is a common UX mistake also affecting a11y.

**Resources:**

- https://radicle.zulipchat.com/#narrow/stream/369278-web/topic/small.20design.20issues.20pt.20II/near/405115920

**Comment by QZera** [comment]
# Results

An issue status indicator icon has been added to each card. Hovering it opens a tool-tip with the status name.



![Image](https://github.com/cytechmobile/radicle-planning-boards/assets/15063937/e0c9ccdd-cbc2-4513-b0ea-676cac216989)



![Image](https://github.com/cytechmobile/radicle-planning-boards/assets/15063937/8c21ba1e-578a-4270-b6d7-4899846cc606)
