### ISSUE TITLE
Allow re-ordering issues within a column and persist ordering

### ISSUE THREAD

**Issue by maninak** [cytechmobile/radicle-planning-boards#21]
Instead of storing the index of a card in the column we should perhaps store which card it should be shown after (and perhaps before? not needed I think).

This will effectively create a singly linked list. The benefits of this approach are:

- when re-ordering Issue cards we only have to update the related links (complexity `O(1)`) and not the indices of _all cards_ under the one we moved (including the moved one) in that category. Worse yet, moving across columns means we need to update index metadata for even more Issues (complexity `O(M+N)`).
- after parsing a single ticket in a category we can much quicker recreate a specific column and ignore processing issues of no-longer used/archived columns (approach scales for projects with thousands of issues)

**Comment by QZera** [comment]
# Results

- Added support for persisting issue order through issue labels


https://github.com/cytechmobile/radicle-planning-boards/assets/15063937/10bc2eeb-85fa-4ddc-a2ba-4e3188d83e81
