### ISSUE TITLE
Radicle Issue cards (mock data) shown in Columns

### ISSUE THREAD

**Issue by maninak** [cytechmobile/radicle-planning-boards#4]
**Spec**
- available columns
  - (uncategorized?)
  - To do
  - Doing 
  - Done

**Out of scope:**
- no header, footer, anything other than a couple of columns
- column
  - title
- card (hardcoded json/[POJO](https://masteringjs.io/tutorials/fundamentals/pojo))
  - id (eyebrow)
  - title

**Resources**

- https://app.radicle.xyz/seeds/seed.rhizoma.dev/rad:z3yQUb9HDAC7TQrUDGkQsXDsYFj9G/tree/master/api/radicle-httpd.yaml#L788

**Comment by QZera** [comment]
Here is what the Columns and Cards ended up looking like.
Stuck to the radicle design language. Kept it pretty minimal, but both `Column` and `IssueCard` components can be enriched pretty easily.

Very open to feedback!

![Image](https://github.com/cytechmobile/radicle-planning-boards/assets/15063937/4ba46160-fa20-42c0-aa68-2af95efe0f87)

**Comment by maninak** [comment]
I got a few minor UI improvement suggestions for hopefully better UX:

- I'd change the color of the ID text to be the same as that of the title with something like `text-rad-foreground-dim` since there's no reason to pull the user's attention so much on secondary content.
- I'd also check if increasing the font-size difference between title and id would help visually make out the content priorities contrast better. 
- I'd increase the gutter/spacing between columns to be much larger than the padding between the cards and the column so that the vertical lines don't come too close together in the eye
- I'd remove the border/outline form the cards themselves. Using `bg-rad-background-float` and `hover:bg--rad-fill-float-hover` as colors should be enough to make the cards stand out visually and help reduce border/line nesting which gets noisy pretty quickly

Already looks like a legit thing issue board, well done!

**Comment by QZera** [comment]
Thanks for the feedback!

Agreed with and applied most of it.*

* About the last point (removing the borders from the cards): The contrast was a bit too low, so I ended up changing the background of the columns to `bg-rad-background-dip` to compensate for the lack of border.



![Image](https://github.com/cytechmobile/radicle-planning-boards/assets/15063937/cb9971a1-2113-4110-a9de-f20a2259c08c)

**Comment by QZera** [comment]
## Results

Implemented basic UI with issue cards and columns using Radicle colors

![Image](https://github.com/cytechmobile/radicle-planning-boards/assets/15063937/addaa6d8-0563-467f-a2ea-82f8d2b856e3)
