### ISSUE TITLE
PR Linting GitHub action failing

### ISSUE THREAD

**Issue by QZera** [cytechmobile/radicle-planning-boards#43]
The repo's PR linting action is consistently failing which doesn't allow PRs to be merged.

**Comment by QZera** [comment]
There is an [open issue](https://github.com/JulienKode/pull-request-name-linter-action/issues/224) on the action repo.

Will remove the action for now, and re-introduce it once the issue has been resolved.

**Comment by gsaslis** [comment]
@QZera did you try out the workaround ?

**Comment by gsaslis** [comment]
https://github.com/JulienKode/pull-request-name-linter-action/issues/224#issuecomment-1672053886

**Comment by QZera** [comment]
@gsaslis I didn't. 

I gave it a shot now and it seems to work!
