### ISSUE TITLE
Allow moving a card across columns

### ISSUE THREAD

**Issue by maninak** [cytechmobile/radicle-planning-boards#5]
**Implementation**

Can be drag&drop or not (e.g. via a 3-dot menu where the user selects target column), whichever is quickest to implement.

**Resources:**
- [VueDraggablePlus](https://alfred-skyblue.github.io/vue-draggable-plus/en/) (blessed by [Evan](https://twitter.com/youyuxi/status/1726975120756126179))

**Comment by QZera** [comment]
## Results
- Implemented drag&drop functionality which allows for changing both the column as well as the order of the cards
- Added icons and card counters to the Column headers


https://github.com/cytechmobile/radicle-planning-boards/assets/15063937/aa09fca4-e5e2-4f0d-a203-cb1671066d4b
