### ISSUE TITLE
Create httpd client architecture

### ISSUE THREAD

**Issue by gsaslis** [cytechmobile/radicle-planning-boards#6]
We need to setup the infrastructure to make requests to httpd in an idiomatic and typesafe way. We could come up with our own solution, or use what's on radicle-interface, or use what's on the vscode extension or use an OpenAPI based client (an option that wasn't available before, when the Open API spec wasn't officially maintained).

**Resources:**

- https://github.com/enkot/nuxt-open-fetch
- https://openapi-ts.pages.dev/openapi-fetch/
- https://app.radicle.xyz/nodes/seed.radicle.xyz/rad:z4V1sjrXqjvFdnCUbxPFqd5p4DtH5/tree/httpd-client/index.ts#L140
- https://app.radicle.xyz/nodes/seed.radicle.garden/rad:z3Makm6fsQQXmpSFE43DZqwupaEhk/tree/src/helpers/fetchFromHttpd.ts

**Comment by maninak** [comment]
@carboniq-dev prompted by [this discussion](https://radicle.zulipchat.com/#narrow/stream/369277-heartwood/topic/document.20the.20HTTPD.20API) I did a bit more research, found and added nuxt-open-fetch to the resources which looks very promising.

**Comment by maninak** [comment]
Hey @carboniq-dev I looked into the `nuxt-open-fetch` issue we talked about today in our call "error accessing onRequest of undefined" for v0.2.2 and "error 500 createOpenFetch is not defined" for v0.3.0.

It looks like this lib is too buggy for now, unfortunately, so unless something changes we should go with another alternative. I'm watching the status of https://github.com/enkot/nuxt-open-fetch/pull/17 which closes  https://github.com/enkot/nuxt-open-fetch/issues/18 to re-consider in the future.

When/if they ever get this lib into a working state it would be a really clean solution. Until then I'd say let's just cut our losses and implement whatever you deem is the quickest solution (perhaps copy-paste the lib from radicle-interface?).

**Comment by maninak** [comment]
@trc-mathieu if you have a related code sample or a guide to share it would help a lot. Specifically on how to "use the module as a local Nuxt module". Thank you so much for coming over to assist!

**Comment by trc-mathieu** [comment]
Sure, simply create these fodlers in your nuxt project called `modules/nuxt-open-fetch`. Clone this repo and then copy paste the `src` into `modules/nuxt-open-fetch`. Then in your `nuxt.config.ts`, simply add ` modules: ["./modules/nuxt-open-fetch/src/module.ts"]`.
You can then follow the documentation and everything should work.

**Comment by maninak** [comment]
After following [this guide](https://nuxt-open-fetch.vercel.app/advanced/custom-plugin) it indeed worked with v0.3.0. Thanks @trc-mathieu 

![image](https://github.com/cytechmobile/radicle-planning-boards/assets/7542054/96edb7e6-fbd2-4f0d-a153-dcad018b0120)

**Comment by QZera** [comment]
I want to raise some concerns about using `nuxt-open-fetch` after reading up and playing around with it a bit.

Overall I think it's great how it integrates with the existing data-fetching of Nuxt (which after reading up on it, seems pretty robust). And for the most part it seems to behave as expected.

However, as it stands there are 2 issues:
1.  The OpenAPI spec doesn't seem to include the query params of the endpoints (e.g. `perPage`). As a result when trying to add them in `useHttpdFetch` there is a typescript error. 
This raises a deeper concern we could face down the road, "how accurate is the OpenAPI spec?" given that we're completely relying on it if we use this package.
2. The type of the data returned seems to have been "DeepPartial-ed", meaning all properties are optional. (e.g. `Issue { id?: string, title?: string, ... }`

I also think this package is a bit too early in development (so we can expect a lot of breaking changes as we update it).

All that said, I don't want to drag this issue any longer, so give the circumstances I think we can "live" with these issues, so I'm going to proceed with the open PR.
@maninak If you think these issues are a deal breaker, I can very quickly replace it with `useFetch` instead.

**Comment by maninak** [comment]
Hey @QZera, both valid concerns. The latter you may find has been mentioned on [zulip](https://radicle.zulipchat.com/#narrow/stream/369277-heartwood/topic/document.20the.20HTTPD.20API), the former is not as well as others like payloads for post requests etc.

The expectation is that that the httpd OpenApi spec will eventually become auto-generated from source code or at least patched to be more accurate by hand. Until then we could also use a local copy instead of the remote-hosted original file, and patch what we need, though it would be a manual process and we'd need keep up with their changes manually, so overall it sounds like a worse alternative right now.
 
For the intents and purposes of this ticket and phase (R&D) we've proven from our side we have the capability for what needs to be done. In our source code, it will kinda suck, but we can prob hack around with type assertions like `as Issue` where Issue is defined in a `types/httpd.ts` as something like

```ts

**Comment by QZera** [comment]
## Result

An client for httpd was implemented leveraging the [nuxt-open-fetch](https://github.com/enkot/nuxt-open-fetch) package. The client will be used to fetch and mutate data in future PRs.
